---
version: 3
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/ansible-runner:latest
  EE_BUILDER_IMAGE: quay.io/ansible/ansible-builder:3.0.0
additional_build_steps:
  prepend_base: |
    RUN pip3 install --upgrade pip
    RUN pip3 install --upgrade pyopenssl
  append_base: |
    RUN pip3 install --upgrade ansible-runner